### ISSUE TITLE
Correct code along for prepend on consultant[:surname] demo

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/ruby-vs-js-hash-dictionary#11]
When `.prepend` is executed on `consultant[:surname]`, it modifies the hash. The README.md states that it doesn't modify, just returns the change. Correction needed to show that the hash will be modified from the `.prepend`

**Comment by payne-chris-r** [comment]
prepend modifies inline--this code isn't accurate anymore: 
> consultant[:surname].prepend 'O\''
=> "O'Donovan"
> consultant[:surname]
=> "Donovan"
> consultant[:surname] = consultant[:surname].prepend 'O\''
=> "O'Donovan"
> consultant[:surname]
=> "O'Donovan"

**Comment by laurenfazah** [comment]
Fix is coming in merge from `013/master` branch

**Comment by payne-chris-r** [comment]
Looks good. Thanks @laurenfazah
