### ISSUE TITLE
Show `.delete(<key>)`?

### ISSUE THREAD

**Issue by laurenfazah** [ga-wdi-boston/ruby-vs-js-hash-dictionary#13]

**Comment by neugierige** [comment]
@jrhorn424 @gaand - I'd be glad to add this into the talk, but I will leave this to you to determine

**Comment by gaand** [comment]
I think it might be worth including.  Especially if it seems like something that should be part of the learning objectives.

**Comment by neugierige** [comment]
I will add this to one of the demos, and include it in the objectives. Stay tuned.
