### ISSUE TITLE
alternate metaphor to "consultant" and "weight" example?

### ISSUE THREAD

**Issue by neugierige** [ga-wdi-boston/ruby-vs-js-hash-dictionary#15]
I see that the example of a consultant and his/her fluctuating weight has been part of this lesson since (at least) cohort 10. Would it be possible to move away from this, and use a different metaphor? 

For example, I was thinking of using an "apartment" as the metaphor, which would have set number of rooms, number of roommates/pets, which would connect this new thing to what we had previously done in the JS lessons, without explicitly doing a comparison to JS. 

Looking forward to your input, @gaand, @jrhorn424

**Comment by gaand** [comment]
I'm okay with picking a different example, but I think part of the reason for using weight is that it's a property that changes.

**Comment by neugierige** [comment]
Yes, I neglected to mention that "temperature" would be the thing that would fluctuate. I will write this out and let you review it.
