### ISSUE TITLE
Add linter configurations for comparison to JS

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ruby-vs-js-hash-dictionary#5]
1.  `git remote add js-template git@github.com:ga-wdi-boston/js-template`
1.  `git fetch js-template`
1.  `git checkout js-template/master -- .jshintrc .jshintignore .jscsrc`

**Comment by laurenfazah** [comment]
Coming with merge-to-be from `013/master` branch

**Comment by jrhorn424** [comment]
Awesome. Thanks!
