### ISSUE TITLE
Move block initializer to later/end

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-vs-js-hash-dictionary#6]
Possibly confusing.

**Comment by gaand** [comment]
The block default construct is still in the demonstration.

**Comment by gaand** [comment]
Also, you might want to have a simple example like that as well as the link to the more detailed example.

**Comment by payne-chris-r** [comment]
@gaand I think this has been done as well. It's now in the lab/bonus at the end. It's still very present in the documentation, but that's unavoidable. Let me know if we can close.
